#cloud-config
---
# avoid auto-upgrade kicking off in the first boot
bootcmd:
  - [cloud-init-per, once, touch, /var/lib/apt/periodic/update-success-stamp]

users:
  - name: egi
    gecos: EGI
    primary_group: egi
    groups: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:enolfc
      - gh:gwarf
      - gh:CatalinCondurache
      - gh:sebastian-luna-valero

write_files:
  - content: |
      # Created by cloud-init according to:
      #    https://github.com/EGI-Federation/fedcloud-dashboard/blob/main/deployment/cloud-init.yaml
      #
      # 1. Access is restricted to members of the vo.cloud.egi.eu VO with the auditor role
      #    urn:mace:egi.eu:group:cloud.egi.eu:role=auditor#aai.egi.eu
      #
      # 2. Once logged in, they have unrestricted sudo power:
      %egi-eu_cloud-egi-eu ALL=(ALL) NOPASSWD:ALL
    path: /etc/sudoers.d/motley
    permissions: "0644"
