---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: "grycap.motley_cue"
      ssh_oidc_other_vos_name: cloud.egi.eu
      ssh_oidc_other_vos_role: auditor
    - role: "fedcloud-dashboard"
      fedcloud_dashboard_dns: dashboard.test.fedcloud.eu
