---
name: Check links

on: [push, pull_request]

jobs:
  markdown-link-check:
    name: Check links using markdown-link-check
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      # see https://github.com/actions/checkout/issues/766
      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v3.0.1

      - name: Check links on new changes
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".github/linters/mlc_config.json"
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          base-branch: "main"
