---
name: Lint

on: pull_request

permissions: read-all

jobs:
  super-lint:
    name: Lint with Supper-Linter
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter on new changes
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only check new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Fail on errors
          DISABLE_ERRORS: false
          VALIDATE_CHECKOV: false
